#ifndef RESOURCES_H	// -*- tab-width:8; c-basic-offset:2; -*-
#define RESOURCES_H 1
// DeckDll: standalone and integrated deckbuilder.

#define RES_ICON				101
#define RES_ACCEL				102

#define RES_BUTTON_OK				1
#define RES_BUTTON_CANCEL			2

#define RES_SELLMENU_SELLCARDFORX		1

#define RES_MAINMENU_BUTTON_STATS		6
#define RES_MAINMENU_NEWDECK			11
#define RES_MAINMENU_LOADDECK			12
#define RES_MAINMENU_SAVEDECK			13
#define RES_MAINMENU_MUSIC			14
#define RES_MAINMENU_EFFECTS			15
#define RES_MAINMENU_EXIT			16
#define RES_MAINMENU_MINIMIZE			18
#define RES_MAINMENU_BUTTON_DECKINFO		19
#define RES_MAINMENU_BUTTON_EXIT		20
#define RES_MAINMENU_BUTTON_DECK_1		21
#define RES_MAINMENU_BUTTON_DECK_2		22
#define RES_MAINMENU_BUTTON_DECK_3		23

#define RES_FILTERMENU_GOLD_ALL			1
#define RES_FILTERMENU_GOLD_MATCHINGALL		2
#define RES_FILTERMENU_GOLD_MATCHINGANY		3
#define RES_FILTERMENU_LAND_LANDANDMANA		4
#define RES_FILTERMENU_LAND_LANDONLY		5
#define RES_FILTERMENU_LAND_MANAONLY		6
#define RES_FILTERMENU_ARTIFACT_CREATURES	7
#define RES_FILTERMENU_ARTIFACT_NONCREATURES	8
#define RES_FILTERMENU_CREATURE_CREATURE	9
#define RES_FILTERMENU_CREATURE_TOKEN		10
#define RES_FILTERMENU_CREATURE_ARTIFACT	11
#define RES_FILTERMENU_CREATURE_LIST		12
#define RES_FILTERMENU_ENCHANTMENT_ENCHANTMENTS	13
#define RES_FILTERMENU_ENCHANTMENT_WORLD	14
#define RES_FILTERMENU_ENCHANTMENT_LAND		15
#define RES_FILTERMENU_ENCHANTMENT_CREATURE	16
#define RES_FILTERMENU_ENCHANTMENT_ARTIFACT	17
#define RES_FILTERMENU_ENCHANTMENT_ENCHANT	18
#define RES_FILTERMENU_ENCHANTMENT_PERMANENT	19
#define RES_FILTERMENU_ENCHANTMENT_PLAYER	20
#define RES_FILTERMENU_ENCHANTMENT_INSTANT	21
#define RES_FILTERMENU_COST_GREATER		22
#define RES_FILTERMENU_COST_LESSER		23
#define RES_FILTERMENU_COST_EQUAL		24
#define RES_FILTERMENU_COST_X			25
#define RES_FILTERMENU_POWER_GREATER		26
#define RES_FILTERMENU_POWER_LESSER		27
#define RES_FILTERMENU_POWER_EQUAL		28
#define RES_FILTERMENU_TOUGHNESS_GREATER	29
#define RES_FILTERMENU_TOUGHNESS_LESSER		30
#define RES_FILTERMENU_TOUGHNESS_EQUAL		31
#define RES_FILTERMENU_ABILITY_NATIVE		32
#define RES_FILTERMENU_ABILITY_GIVES		33
#define RES_FILTERMENU_ABILITY_FLYING		34
#define RES_FILTERMENU_ABILITY_FIRSTSTRIKE	35
#define RES_FILTERMENU_ABILITY_TRAMPLE		36
#define RES_FILTERMENU_ABILITY_REGENERATION	37
#define RES_FILTERMENU_ABILITY_BANDING		38
#define RES_FILTERMENU_ABILITY_COLORWARD	39
#define RES_FILTERMENU_ABILITY_LANDWALK		40
#define RES_FILTERMENU_ABILITY_POISON		41
#define RES_FILTERMENU_ABILITY_RAMPAGE		42
#define RES_FILTERMENU_ABILITY_REACH		43
#define RES_FILTERMENU_ABILITY_STONING		44
#define RES_FILTERMENU_ABILITY_VIGILANCE	45
#define RES_FILTERMENU_ABILITY_HASTE		46
#define RES_FILTERMENU_RARITY_COMMON		47
#define RES_FILTERMENU_RARITY_UNCOMMON		48
#define RES_FILTERMENU_RARITY_RARE		49
#define RES_FILTERMENU_RARITY_RESTRICTED	50
#define RES_FILTERMENU_RARITY_BANNED		51
#define RES_FILTERMENU_MAINMENUBUTTONS_ON	52
#define RES_FILTERMENU_MAINMENUBUTTONS_OFF	53
#define RES_FILTERMENU_FOURTH_UNLIMITED		54
#define RES_FILTERMENU_FOURTH_REVISED		55
#define RES_FILTERMENU_FOURTH_FOURTH		56
#define RES_FILTERMENU_EXPANSIONLIST		57

#define RES_DIALOG_ASK_VALUE			127
#define RES_DIALOG_FILTER_LIST			128
#define RES_DIALOG_DECKINFO			197
#define RES_DIALOG_DECKSTATS			198
#define RES_DIALOG_INFOBOX			199
#define RES_DIALOG_GROUPMOVE			200
#define RES_DIALOG_LOADDECK			221

#define RES_MENU_CONSOLIDATE			200
#define RES_MENU_REFRESH			201
#define RES_MENU_CLEARDECK			202
#define RES_MENU_RESTOREDECK			203
#define RES_MENU_NEWDECK			204
#define RES_MENU_LOADDECK			205
#define RES_MENU_SAVEDECK			206
#define RES_MENU_EXIT				207
#define RES_MENU_SORTDECK			208
#define RES_MENU_MUSIC				209
#define RES_MENU_EFFECTS			210
#define RES_MENU_MINIMIZE			211
#define RES_MENU_COLORINTODECK			212
#define RES_MENU_COLOROUTOFDECK			213

#define RES_ASKVALUE_EDITTEXT			1000

#define RES_FILTERLIST_LISTBOX			1001
#define RES_FILTERLIST_SELECTALL		1002
#define RES_FILTERLIST_CLEARALL			1003
#define RES_FILTERLIST_ENABLEFILTER		1007

#define RES_LOADDECK_DECKLIST			1003
#define RES_LOADDECK_PLAYERDECK			65535

#define RES_DECKINFO_DESCRIPTION_EDITTEXT	1015
#define RES_DECKINFO_NAME_EDITTEXT		1016
#define RES_DECKINFO_EMAIL_EDITTEXT		1017
#define RES_DECKINFO_DECKTITLE_EDITTEXT		1018
#define RES_DECKINFO_DATE_EDITTEXT		1019
#define RES_DECKINFO_COMMENT_EDITTEXT		1020
#define RES_DECKINFO_VERSION_EDITTEXT		1023
#define RES_DECKINFO_DECKTITLE			1028
#define RES_DECKINFO_DESCRIPTION		1029
#define RES_DECKINFO_NAME			1030
#define RES_DECKINFO_EMAIL			1031
#define RES_DECKINFO_DATE			1032
#define RES_DECKINFO_COMMENT			1034
#define RES_DECKINFO_VERSION			1035

#define RES_INFOBOX_LIST			1043
#define RES_INFOBOX_DESCRIPTION			1050

#define RES_GROUPMOVE_BUTTON_WHITE		1044
#define RES_GROUPMOVE_BUTTON_RED		1045
#define RES_GROUPMOVE_BUTTON_GREEN		1046
#define RES_GROUPMOVE_BUTTON_BLUE		1047
#define RES_GROUPMOVE_BUTTON_BLACK		1048
#define RES_GROUPMOVE_BUTTON_ARTIFACT		1049

#define RES_FULLCARDMENU_EXPAND			4001
#define RES_UNK			4002

#endif
